### ISSUE TITLE
awe he had to re-upload the whole project

### ISSUE THREAD

**Issue by noahmajors** [Phxnt0mWare/Phxnt0mWare#3]
about time you obfuscated my project lol. as for the dualhook, I hope you learned your lesson:) Don’t let me find another one in there or I’ll make sure your whole repo gets taken down;)

luv @knownasnosh on discord

**Comment by Phxnt0mWare** [comment]
my ass nigga

**Comment by noahmajors** [comment]
🥰 just learn to not skid

**Comment by noahmajors** [comment]
message me on discord bb 😔😩
